config/routes.rb
NflApp::Application.routes.draw do
  resources :users
  resources :coaches
  resources :teams
  resources :sessions, only: [:new, :create, :destroy]

  root              to: 'basic_pages#home'
  match '/help',    to: 'basic_pages#help'
  match '/about',   to: 'basic_pages#about'
  match '/contact', to: 'basic_pages#contact'
  match '/ari',     to: 'basic_pages#ari'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/teams',   to: 'teams#index'

end

app/models/coach.rb
# == Schema Information
#
# Table name: coaches
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  team            :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class Coach < ActiveRecord::Base
  attr_accessible :name, :team, :password, :password_confirmation
  has_secure_password

  VALID_NAME_REGEX = /[A-Z][a-z]+\.[A-Z][a-z]+/
  validates(:name, presence: true, length: { maximum: 50 }, format: {with: VALID_NAME_REGEX}, uniqueness: true )
  validates(:team, presence: true)

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :integer          not null
#  team       :string(255)
#  abbrev     :string(255)      primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  url        :string(255)
#  division   :string(255)
#

class Team < ActiveRecord::Base
  has_one :user

  self.primary_key = :abbrev
  attr_accessible :abbrev, :team, :url, :division

  validates :team, presence: true, uniqueness: { case_sensitive: false }
  validates :abbrev, presence: true, length: { maximum: 3 }, uniqueness: { case_sensitive: false }
  validates :url, presence: true
  validates :division, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  coach           :boolean          default(FALSE)
#  team            :string(255)
#  teamname        :string(255)
#  team_id         :string(255)
#

class User < ActiveRecord::Base
  belongs_to :team

  attr_accessible :name, :email, :password, :password_confirmation, :team_id, :coach
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def ari
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController

  def show
    @coach = Coach.find(params[:id])
  end

  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def show
    @team = Team.find(params[:id])
  end

  def new
  end

  def index

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :coach_user,     only: :destroy

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render :xml => @user }
      format.json { render :json => @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
      format.xml { render :xml => @user }
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the NFL Rails App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.paginate(page: params[:page])

    respond_to do |format|
      format.html
      format.xml { render :xml => @users }
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def coach_user
      redirect_to(root_path) unless current_user.coach?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "NFL Rails App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/teams_helper.rb
require 'net/http'

module TeamsHelper

  def find_team (city)
    @game_id = 17;
    @count = 0;
    @json_object["gms"].each do |game|
      if game["h"] == city
        @game_id = @count
      elsif game["v"] == city
        @game_id = @count * -1
      end
      @count = @count + 1;
    end
    @game_id
  end

  def get_score(team)
    uri = URI.parse("http://www.nfl.com/liveupdate/scorestrip/ss.json")
    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Get.new(uri.request_uri)
    request["X-ApiKey"] = "InQu_g8rey_8kFDpvgb1m3CYvVySAKx6TE9jSHZoRThZdz0g"

    response = http.request(request)

    @json_object = JSON(response.body)

    city = team.abbrev.upcase

      @game = find_team (city)
      if @game > 0 && @game != 17
        @outcome = "#{@json_object["gms"][@game]["h"]} #{@json_object["gms"][@game]["hnn"]} #{@json_object["gms"][@game]["hs"]}, #{@json_object["gms"][@game]["v"]} #{@json_object["gms"][@game]["vnn"]} #{@json_object["gms"][@game]["vs"]}"
      elsif @game == 17
        @outcome = "BYE Week"
      else
        @outcome = "#{@json_object["gms"][@game * -1]["v"]} #{@json_object["gms"][@game * -1]["vnn"]} #{@json_object["gms"][@game * -1]["vs"]}, #{@json_object["gms"][@game * -1]["h"]} #{@json_object["gms"][@game * -1]["hnn"]} #{@json_object["gms"][@game * -1]["hs"]}"
      end

    @outcome
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/basic_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  This NFL Rails page
  is a project to develop Ruby on Rails skills in a fun and creative environment
  with the help of <a href="http://www.cmu.edu/silicon-valley">Carnegie Mellon Silicon Valley</a>. This
  is the first application done by Adam Olshansky.
</p>

app/views/basic_pages/ari.html.erb
<div class="center hero-unit">
    <% provide(:title, 'Arizona Cardinals') %>

    <h1>Arizona Cardinals</h1>
    <h2>
        The <a href="http://www.azcardinals.com/">Arizona Cardinals</a>
        are a team in the National Football League.  They play in the NFC West Division
        and make their home in Glendale, Arizona at University of Phoenix Stadium.
        They are coached by Ken Whisenhunt.
    </h2>
</div>

<%= link_to image_tag("ari.png", alt: "NFL"), 'http://www.azcardinals.com/' %>

<h2>
  Most recent game score:
</h2>


<h3>
    NFC West:
</h3>
<h4>
    <a href=teams/ari>Arizona Cardinals</a>
</h4>
<h4>
    <a href=teams/sf>San Francisco 49ers</a>
</h4>
<h4>
  <a href=teams/sea>Seattle Seahawks</a>
</h4>
<h4>
  <a href=teams/stl>St. Louis Rams</a>
</h4>

<h3>
  NFC North:
</h3>
<h4>
  <a href=teams/chi>Chicago Bears</a>
</h4>
<h4>
  <a href=teams/det>Detroit Lions</a>
</h4>
<h4>
  <a href=teams/gb>Green Bay Packers</a>
</h4>
<h4>
  <a href=teams/min>Minnesota Vikings</a>
</h4>

<h3>
  NFC South:
</h3>
<h4>
  <a href=teams/atl>Atlanta Falcons</a>
</h4>
<h4>
  <a href=teams/car>Carolina Panthers</a>
</h4>
<h4>
  <a href=teams/no>New Orleans Saints</a>
</h4>
<h4>
  <a href=teams/tb>Tampa Bay Buccaneers</a>
</h4>

<h3>
  NFC East:
</h3>
<h4>
  <a href=teams/dal>Dallas Cowboys</a>
</h4>
<h4>
  <a href=teams/nyg>New York Giants</a>
</h4>
<h4>
  <a href=teams/phi>Philadelphia Eagles</a>
</h4>
<h4>
  <a href=teams/was>Washington Redskins</a>
</h4>

<h3>
  AFC West:
</h3>
<h4>
  <a href=teams/den>Denver Broncos</a>
</h4>
<h4>
  <a href=teams/kc>Kansas City Chiefs</a>
</h4>
<h4>
  <a href=teams/oak>Oakland Raiders</a>
</h4>
<h4>
  <a href=teams/sd>San Diego Chargers</a>
</h4>

<h3>
  AFC North:
</h3>
<h4>
  <a href=teams/bal>Baltimore Ravens</a>
</h4>
<h4>
  <a href=teams/cin>Cincinnati Bengals</a>
</h4>
<h4>
  <a href=teams/cle>Cleveland Browns</a>
</h4>
<h4>
  <a href=teams/pit>Pittsburgh Steelers</a>
</h4>

<h3>
  AFC South:
</h3>
<h4>
  <a href=teams/hou>Houston Texans</a>
</h4>
<h4>
  <a href=teams/ind>Indianapolis Colts</a>
</h4>
<h4>
  <a href=teams/jac>Jacksonville Jaguars</a>
</h4>
<h4>
  <a href=teams/ten>Tennessee Titans</a>
</h4>

<h3>
  AFC East:
</h3>
<h4>
  <a href=teams/buf>Buffalo Bills</a>
</h4>
<h4>
  <a href=teams/mia>Miami Dolphins</a>
</h4>
<h4>
  <a href=teams/ne>New England Patriots</a>
</h4>
<h4>
  <a href=teams/nyj>New York Jets</a>
</h4>

app/views/basic_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  The <a href="http://www.nfl.com/">National Football League</a>
  holds trademarks to all team nicknames and logos.
  Please contact
  <a href="mailto:adam.olshansky@sv.cmu.edu">Adam Olshansky</a>
  for more information for this site.
</p>

app/views/basic_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This is a Rails website to show NFL scores for your favorite team.  Please visit the
  <a href="http://www.nfl.com/scores">NFL.com Scores Page</a> for more in-depth analysis.
  To navigate to your particular teams page, please enter the identifier for the team at the end of the URL.
  For example, for the Arizona Cardinals, navigate to:
  <a href=teams/ari>nfl.herokuapp.com/teams/ari</a>.

  Alternatively, click on the team on the <a href=/teams>Teams</a> page.
</p>

app/views/basic_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the NFL Rails Page</h1>

  <h2>
    This is the home page for the
    <a href="http://www.nfl.com/">NFL</a>
    Rails App sample application.
  </h2>
  <h2>
    To see your favorite team, click <a href=/teams>here</a>.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("nfl.png", alt: "NFL"), 'http://www.nfl.com/' %>

app/views/coaches/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/coaches/new.html.erb</p>

app/views/coaches/show.html.erb
<% provide(:title, @coach.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
  <%= @coach.name %>
      </h1>
        <h2>
            <%= @coach.name %> is the current coach of the <%= @coach.team %>.
        </h2>
    </section>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.nfl.com/">NFL Rails App</a>
    by Adam Olshansky
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.nfl.com/scores/">Scores</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "NFL Rails", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Teams", teams_path %></li>
          <% if signed_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.coach? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up to follow your favorite NFL team!</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <h1>
        <%= @user.team.team %>
      </h1>
    </section>
  </aside>
</div>